name: PackPlugin
on:
    push:
        branches:
            - master
        tags:
            - '*'

env:
    PLUGIN_NAME: FroshPlatformHtmlMinify
    ACCOUNT_USER: ${{ secrets.ACCOUNT_USER }}
    ACCOUNT_PASSWORD: ${{ secrets.ACCOUNT_PASSWORD }}

jobs:
    pack:
        runs-on: ubuntu-latest
        container: ghcr.io/friendsofshopware/platform-plugin-dev:v6.3.4
        steps:
            -   name: Checkout
                uses: actions/checkout@v2.3.1
                with:
                    path: ${{ env.PLUGIN_NAME }}

            -   name: Build & create zip
                run: |
                    ln -s "$(pwd)" "/plugins/${PLUGINNAME}"
                    start-mysql
                    composer install --no-suggest
                    pack-plugin "${PLUGIN_NAME}"

            -   name: Upload Artefact
                uses: actions/upload-artifact@v2
                with:
                    name: ${{ env.PLUGIN_NAME }}
                    path: ${{ env.PLUGIN_NAME }}.zip

            -   name: Validate Zip
                run: plugin-uploader ext:validate $(pwd)/${PLUGIN_NAME}.zip

            -   name: Update store informations
                run: plugin-uploader ext:update $(pwd)/${PLUGIN_NAME}/

            -   name: Upload to store
                if: startsWith(github.ref, 'refs/tags/')
                run: plugin-uploader ext:upload $(pwd)/${PLUGIN_NAME}.zip --createRelease
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
